appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: r/K5PNHO1EPltbEdYAfZqtegYuhld/6c4Kl5rsHro9+fLKEoC3ggrexZ1Au3hcJg7nTMvArvKbONajeouYx9ix4cJ3htKA4CHi8v7Auuhe3nyU2OhNPfpyLGD0iTFbIRt1ozdoMp2dhFxRR/kWADPvw6OK3zh5HwlszR47rAKZU4UXS38Pz6QN6oQ/SoviFLFRqY46H7YYLnFaLRpU+slEl5RT3BrA1STQkxtHocp4TJOCmbZBkCc44FGwSZcRPnpyGetICOqWy3t597OXwt0NR9BqxEQ543N0YTzcGFRQvInSI/xhY37RugOjgYv2azKmUoBTS1hEGPtlpVrqksxSR3GZlLPDp40i+DzfJnRZlFCDWGOwbC/gVxXg++FsYccjVosmstGKpSugnm4jtAxIZ2XDLLOP06y/omc2AvY0yZTWZHeg/IhSqtw0pIpF4cvwvDiZahwDJUcVkkqDPBCGf+UCulgF5Ts/ja1OAD2cQCUHPqifuFydFCLbx5L+sWfMe2aeyn9OrkQSlYkB9zvfJGJ/99ea92JceQsxTh2yQ/sv+Sp0R1qMLG5DkcqfdyT2ebYCdmAx35BPNxewnhzckFa7nC31+NHfcYWOSzDh44V6gj2kGQr/FSsIgRgjR6qLThKR2h0vgmb8NlFNaNwklu4Uzcs0/DWmDCXBIfgK0=
conda_forge_output_validation: false
